### ISSUE TITLE
Change units to Imperial

### ISSUE THREAD

**Issue by Sushiwondough** [mclarence/StatBar#1]
I wanted to know how to change unites to Fahrenheit. I went and changed all the unit=metric to unit=imperial, and now I went from 11°C to 52°C. How can I change the C to F? If you couldn't tell already I know absolutely nothing about coding. Any help is appreciated :D

**Comment by mclarence** [comment]
Line 220 in index.jsx, replace C with F at the end of the line. The C symbol was hardcoded.
